version: '3.8'

services:
  product:
    image: python:3.8-slim
    volumes:
      - ./product:/app
    command: python /app/server.py
    ports:
      - "3000:3000"
    depends_on:
      - details
      - reviews-v1
      - reviews-v2
      - reviews-v3

  reviews-v1:
    image: openjdk:11
    volumes:
      - ./reviews-v1:/app
    command: java -jar /app/reviews.jar
    ports:
      - "3001:3001"
    depends_on:
      - ratings

  reviews-v2:
    image: openjdk:11
    volumes:
      - ./reviews-v2:/app
    command: java -jar /app/reviews.jar
    ports:
      - "3002:3002"
    depends_on:
      - ratings

  reviews-v3:
    image: openjdk:11
    volumes:
      - ./reviews-v3:/app
    command: java -jar /app/reviews.jar
    ports:
      - "3003:3003"
    depends_on:
      - ratings

  ratings:
    image: node:12-alpine
    volumes:
      - ./ratings:/app
    command: node /app/server.js
    ports:
      - "3004:3004"

  details:
    image: ruby:2.7-slim
    volumes:
      - ./details:/app
    command: ruby /app/server.rb
    ports:
      - "5005:5005"